apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/sleepr-418104/notifications/production
        name: notifications
        env:
          - name: PORT
            value: "3004"
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 268476247157-knnsdcrsmc2monpr627utkl3kc0s76kv.apps.googleusercontent.com
          - name: SMTP_USER
            value: 86tkstar@gmail.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3004
